# Generated by Django 3.1 on 2020-08-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoPriceChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avitodata', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_parser.avitodata')),
            ],
        ),
    ]
