# Generated by Django 3.1 on 2020-08-24 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0002_avitopricechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avitopricechange',
            name='avitodata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_parser.avitodata'),
        ),
    ]
