# Generated by Django 3.1 on 2020-08-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0003_auto_20200824_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avitodata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_parser.avitodata')),
            ],
        ),
    ]
