# Generated by Django 3.1 on 2020-08-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0004_avitonew'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitodata',
            name='ad_rooms',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='avitodata',
            name='ad_square',
            field=models.CharField(default='2', max_length=120),
        ),
    ]
